sudo: false
language: python
dist: xenial
python:
- "3.5"
- "3.6"
services:
- postgresql
addons:
  postgresql: "9.6"
  apt:
    packages:
    - libgdal-dev
    - postgresql-9.6-postgis-2.4
env:
- UMAP_SETTINGS=umap/tests/settings.py
install:
- pip install .
- pip install -r requirements-dev.txt
script: make test
notifications:
  irc:
    channels:
    - "irc.freenode.net#umap"
    on_success: change
    on_failure: always
  email: false
branches:
  only:
  - master
